# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Headers.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
src
src/generic
src/reflect
)

#
# contents selected with patternfile ??-header--private-generated-headers
#
set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleObjCArchiverFoundation-import-private.h
src/reflect/_MulleObjCArchiverFoundation-include-private.h
)

#
# contents selected with patternfile ??-header--private-generic-headers
#
set( PRIVATE_GENERIC_HEADERS
src/generic/import-private.h
src/generic/include-private.h
)

#
# contents selected with patternfile ??-header--private-headers
#
set( PRIVATE_HEADERS
src/MulleObjCArchiver-Private.h
)

#
# contents selected with patternfile ??-header--public-generated-headers
#
set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleObjCArchiverFoundation-export.h
src/reflect/_MulleObjCArchiverFoundation-import.h
src/reflect/_MulleObjCArchiverFoundation-include.h
)

#
# contents selected with patternfile ??-header--public-generic-headers
#
set( PUBLIC_GENERIC_HEADERS
src/generic/import.h
src/generic/include.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
src/MulleObjCArchiverFoundation.h
src/MulleObjCArchiver.h
src/MulleObjCLoader+MulleObjCArchiverFoundation.h
src/MulleObjCUnarchiver.h
src/NSArchiver+OSBase.h
src/NSArchiver.h
src/NSCoder.h
src/NSKeyedArchiver.h
src/NSKeyedUnarchiver.h
src/NSObject+NSCoder.h
src/NSUnarchiver.h
src/mulle-buffer-archiver.h
src/reflect/_MulleObjCArchiverFoundation-versioncheck.h
)

