#
# This file will be included by cmake/share/sources.cmake
#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/MulleObjCArchiver.m
src/MulleObjCUnarchiver.m
src/NSArchiver+OSBase.m
src/NSArchiver.m
src/NSCoder.m
src/NSKeyedArchiver.m
src/NSKeyedUnarchiver.m
src/NSObject+NSCoder.m
src/NSUnarchiver.m
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCArchiverFoundation.m
)
