      { @selector( MulleObjCArchiver), MULLE_OBJC_NO_CATEGORYID },      // 6c636b4d;MulleObjCArchiver;;
      { @selector( MulleObjCUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // 6c32efb0;MulleObjCUnarchiver;;
      { @selector( MulleObjCUnkeyedArchiver), MULLE_OBJC_NO_CATEGORYID },      // f57df630;MulleObjCUnkeyedArchiver;;
      { @selector( MulleObjCUnkeyedUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // 2b124a0f;MulleObjCUnkeyedUnarchiver;;
      { @selector( NSArchiver), @selector( OSBase) },      // 2a2e712f;NSArchiver;b8ece9a7;OSBase
      { @selector( NSArchiver), MULLE_OBJC_NO_CATEGORYID },      // 2a2e712f;NSArchiver;;
      { @selector( NSCoder), MULLE_OBJC_NO_CATEGORYID },      // 100c54ba;NSCoder;;
      { @selector( NSKeyedArchiver), MULLE_OBJC_NO_CATEGORYID },      // 8a2c6980;NSKeyedArchiver;;
      { @selector( NSKeyedUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // ea42e9ff;NSKeyedUnarchiver;;
      { @selector( NSObject), @selector( NSCoder) },      // b3a66256;NSObject;100c54ba;NSCoder
      { @selector( NSUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // 2b47ff54;NSUnarchiver;;
